### ISSUE TITLE
Comments not working

### ISSUE THREAD

**Issue by Eliottiosdevs** [AndreyBaranchikov/Keinex-iOS#1]
Hi, 

First, AMAZING code, thanks to make this Open Source.
But a question, for the comments, did you use any plugin/code for it because i can't find that.

Thanks,
Eliott Hauteclair

**Comment by AndreyBaranchikov** [comment]
I used this plugin - http://v2.wp-api.org. But I'm not sure that the latest version is fully compatible with the application code.

**Comment by Eliottiosdevs** [comment]
Yes i'm using it too but the api has no comment count and links are different
